// Scripted turns for mock mode. One script per preset topic, plus a generic one for anything else.
// Each script follows the 8-turn arc in docs/PLAN.md: Frame, Challenge, Example, Test,
// Implication, Limits, Common ground, Close. Speaker A speaks odd turns, Speaker B even turns.
import { PRESETS, type SpeakerId, type Temperature } from '@crosstalk/shared';

const AI_BUSINESS = [
  "Let's frame this around leverage rather than replacement. An independent business has always been limited by the owner's hours: one person doing the books, the marketing, the ordering and the actual craft. AI tools are cheapest exactly where those owners are stretched thinnest, in the paperwork around the work. So the useful question isn't whether AI helps small businesses in general. It's which hours an owner gets back, and whether they spend them on the part customers actually come for.",
  "I like 'which hours come back', but I'd challenge the idea that the hours stay with the owner. When every competitor gets the same tools, the time saved tends to become the new baseline, not a gift. If AI makes product descriptions free for one shop, it makes them free for the big chains too, and the chains have more data to tune them with. I'm not sure who ends up ahead, but I wouldn't assume it's the independents.",
  "Fair, so let me make it concrete. Picture a two-person bike repair shop. The owner uses an assistant to answer the same twenty questions about opening hours and tyre sizes, drafts the weekly parts order from last month's invoices, and turns voice notes into repair quotes. None of that is visible to customers. What they notice is that the mechanic is at the bench instead of on the phone. The chains always had staff for that work; the small shop never did.",
  "That example leans on the tool getting things right. What happens when the assistant tells a customer the shop opens at nine on a holiday, or quotes the wrong part? A chain absorbs one bad answer; a two-person shop can lose a regular. There's also subscription creep: five tools at twenty dollars a month each adds up on thin margins. I don't know the typical payback period, and I suspect most owners don't either.",
  "Here's the strongest implication, I think. AI shrinks the minimum size at which a business can look professional. A solo baker can now have clear allergen labels, a decent website and translated menus, things that used to need an agency. That doesn't guarantee they win, but it lowers the cost of starting, and of staying small on purpose. The independents who benefit most may be the ones who use it to stay small, not to grow.",
  "What we haven't said is that the platforms in between still set the terms. If customers find shops through a search engine or a delivery app that also uses AI to rank and summarise them, the owner's careful work can be flattened into a one-line summary they didn't write. And comfort matters: owners who enjoy experimenting will pull ahead of equally good owners who don't. That gap is real, and it has nothing to do with the quality of the bread.",
  "So here's where we agree: AI helps most with the invisible admin, and it's only worth it if the saved time goes back into the thing customers value. Where we're still unsure is who captures the gains once everyone has the same tools, and how much small businesses depend on platforms they don't control. I'd also admit we don't know how often a wrong answer costs a shop a customer. That's an honest gap in what either of us can claim.",
  "I'll close with the questions I'd ask before an owner signs up. Which single task eats the most hours each week, and could a tool do it reliably? What does one wrong answer to a customer cost? Who owns the data you feed in? The practical takeaway: start with one boring task, check the output for a month, and cancel anything that doesn't pay for itself. Small and reversible beats a full overhaul.",
];

const CITIES = [
  "Let's frame this as a question about space, because space is the one thing a city can't make more of. A street is a fixed width, and every metre goes to moving cars, parking them, or people on foot. So 'cars or pedestrians' is really asking which trips a particular street should serve best. A downtown shopping street and a ring road have different answers, and most of the fights come from treating them as the same.",
  "That's a tidy framing, but I'd start somewhere else: who the street is for, not which trips it serves. Trip counts favour whoever travels most, and that tends to be commuters passing through rather than people who live there. A child walking to school makes one short trip a day, yet it may matter more than fifty drivers saving a minute. I'm not sure how to weigh those, but I don't think counting trips settles it.",
  "Then let's look at one street. Imagine a four-lane main road through a town centre, two lanes moving and two parked. The town removes one parking lane, widens the pavement, adds a loading bay for deliveries at set hours, and keeps both through-lanes. Drivers still get through, a little slower. Cafés get outdoor tables. The trade-off is visible and specific, which is what lets people judge it instead of arguing about cars in general.",
  "Let me test what that example assumes. It assumes the drivers who lose parking have somewhere else to go, and that shoppers arrive mostly on foot. Shop owners often believe their customers drive, and they're sometimes wrong, but not always. And what about the person who can't walk far, or the plumber carrying tools? If the change quietly makes the centre harder for them, a nicer pavement hasn't made the street fairer.",
  "Here's what I think follows. Changes like this work best as trials, with paint and planters before concrete, because the arguments are mostly predictions. Cities that test a layout for a summer and count footfall, sales and journey times end up with evidence instead of slogans. And sometimes the result surprises both sides. The practical win is a decision process people can trust, even when they don't like every outcome.",
  "What's overlooked is that a trial measures what's easy to count. Footfall and journey times show up in a spreadsheet; whether older residents feel cut off, or whether a street now belongs to visitors rather than neighbours, doesn't. There's also displacement: traffic pushed off one street lands on another, often a poorer one. A good trial has to ask who absorbed the change, not just whether the main street looks better.",
  "So we agree on more than the title suggests. It's rarely all cars or all people; it's street by street, and the people with the least choice about how they travel deserve the most weight. Where we still differ is how far to trust the numbers, and I'll concede you can't count belonging. What neither of us knows is how long it takes habits to adjust, and whether a short trial ever captures that.",
  "I'll close with the questions worth asking about any street. Who uses it, and who only passes through? Who can't easily change how they travel? Where does the displaced traffic go? The practical takeaway: pick one street, run a reversible trial with measures agreed in advance, and put the people who'd lose out in the room where the result gets judged. That's slower than a slogan, but it holds up.",
];

const FOUR_DAY = [
  "Let's frame this as a question about output, not hours. A four-day week works when a team's results come from focused work that can be compressed, and it struggles where value depends on someone simply being available. So the practical question for an employer isn't whether it's good in general. It's which of our jobs are measured by outcomes and which are measured by coverage. That split, I think, predicts most of the success stories and most of the quiet reversals.",
  "I like the outcomes-versus-coverage split, but I'd push on how clean it is. Most roles are a blend. A software engineer ships features, yet also answers incidents at 4 p.m. on a Friday. A nurse is almost pure coverage. The risk is that a four-day policy quietly becomes four long days plus an unofficial fifth on call. I'm unsure how often that happens, but it's the failure I'd look for first.",
  "Here's a concrete version. Picture a twelve-person accounting firm outside tax season. They close Fridays but rotate one person each week to handle client calls, and that person takes Monday off instead. Output is tracked by files closed, not hours logged. The rotation answers your Friday-incident worry without pretending coverage disappears. It works because the firm can name its coverage needs precisely, a skill many teams have never had to practise.",
  "That example works partly because it's small and seasonal, so let me test the assumptions. It assumes work expands to fill time, so compressing the week mostly removes slack. Sometimes true. But if the team is already at capacity, the same work now needs longer days, and fatigue can erase the gains. Then there's the customer side: if competitors answer on Fridays, does the firm lose clients? I don't know the size of that effect.",
  "The strongest implication, I think, is that a four-day week forces an audit most organisations avoid: what does each meeting, report and approval actually produce? Teams that try it tend to cut recurring meetings first, because that's where time is easiest to recover. Even if a company returns to five days, that audit can be the lasting benefit. The schedule becomes a forcing function for deciding what work is worth doing at all.",
  "What's being overlooked is who absorbs the friction. Salaried knowledge workers may gain a day. Hourly staff might lose pay if hours are cut, or gain exhausting ten-hour shifts. Managers often cover gaps informally. And small businesses with thin margins have less room to run a trial and recover from a bad one. So 'practical' depends heavily on whether the business can afford to be wrong for a quarter.",
  "So here's where we agree: a four-day week is a design problem, not a perk. It needs explicit coverage plans, output measures people trust, and a time-boxed trial with a real exit. Where we're still uncertain: how much of the gain comes from the extra day itself versus the cleanup it forces, and whether results from early adopters, who chose to try it, carry over to firms that would adopt it reluctantly.",
  "I'll close with the questions I'd want answered before trying it. Which roles are coverage roles, and who covers them? What single output measure would we watch, and what number would make us stop? How do hourly staff come out financially? The practical takeaway: run it as a three-month experiment on one team, measure before and after, and treat going back to five days as an acceptable result, not a failure.",
];

const RESTAURANT = [
  "Let me start at a table. A family of four sits down, and nobody has to wave for the bill, explain an allergy twice, or wait while the kitchen guesses. The food arrives warm, and the room is quiet enough to talk. I think the ideal future restaurant is less about robots and more about removing the small frictions that spoil a meal, so the people working there can spend their attention on the part only people can do.",
  "I'd push back on removing all friction, because some friction is the meal. Waiting for the waiter to notice you is annoying; the waiter remembering your name is the reason you come back. Every 'frictionless' restaurant I can picture looks like an airport lounge with better lighting. So my question is what a restaurant is actually for. If it's only efficient food delivery, the ideal future restaurant is your own kitchen and an app.",
  "Then let me tell you about a small place I can picture clearly. Twelve tables, one set menu that changes weekly, ordered when you book. Because the kitchen knows the numbers in advance, almost nothing is thrown away, and the price is lower. The servers don't take orders, so they talk: where the fish came from, why the dessert is sour on purpose. Technology does the planning in the background. The evening still feels hosted, not processed.",
  "That sounds lovely, and also like a place you can't wander into on a Tuesday because you're hungry. Pre-ordering assumes diners plan ahead and never change their minds, which describes almost nobody I've eaten with. What about the spontaneous meal, the picky child, the friend who announces a new diet at the table? I don't know how big that crowd is, but a lot of restaurants survive on walk-ins.",
  "The strongest implication, I think, is that there won't be one ideal restaurant but a clearer split. Some places become planned, low-waste evenings with a story to tell. Others become fast, flexible and cheap, with machines doing more of the cooking. The interesting future is that each can be honest about what it is, instead of every restaurant trying to be a little of everything and doing none of it well.",
  "Here's what we've skipped: the people in the kitchen. Low waste and set menus are great until you're the cook working a split shift for wages that haven't moved in years. Automation might take the worst jobs, or it might take the steady ones and leave the stressful ones. And rent decides more restaurant futures than any menu idea. The ideal restaurant you can't afford to open is, technically, a very nice daydream.",
  "So here's our common ground: the best future restaurants use technology for planning and waste, and keep people for welcome and judgement. We both care about the meal feeling hosted. What's still uncertain is whether that model pays the staff fairly, and whether it can serve walk-ins as well as planners. I'll concede that a beautiful menu doesn't count for much if the kitchen can't keep its cooks.",
  "I'll close with the questions I'd put to anyone designing one. Who gets the hours the machines save? What happens when a guest walks in without booking? How does the place survive if the rent doubles? The practical takeaway: borrow one idea, like a weekly set menu or smarter bookings, try it for a season, and keep whatever makes both guests and cooks happier. Also, keep the bread basket. Some traditions are load-bearing.",
];

const GOLF = [
  "Let's frame this by asking what golf's character actually is. I'd say it's three things: you play the ball as it lies, you keep your own score honestly, and the course is the opponent. Technology that helps people learn, practise and enjoy those things fits. Technology that removes them doesn't. So the line isn't between old and new. It's between tools that support the player's judgement and tools that replace it.",
  "That's a generous line, but I'd challenge how cleanly it holds. Rangefinders were once seen as replacing judgement; now they're normal at most clubs. Drivers and balls have made long courses feel short. Each change looked small and helpful at the time. My worry is that character erodes one reasonable upgrade at a time, and nobody can point to the day it changed. I'm not certain that's happening, but it's the pattern I'd watch.",
  "Here's a concrete case. A beginner uses a launch monitor at the range and learns their misses come from the club face, not their swing path. Two lessons later, they're enjoying a round instead of searching for balls. On the course nothing has changed: same rules, same honest score, same bunker on the fourteenth. That's technology improving golf for one person without touching its character. And plenty of beginners quit in their first year.",
  "That example works because the technology stays at the range. Let me test what happens when it follows players onto the course. If a watch reads the green's slope and suggests the line, is that still your read? Rules bodies already limit some devices in competition, which tells you the line is real and contested. And cost matters: if improving depends on expensive gadgets, the game gets a little more exclusive. I don't know where most clubs draw that line.",
  "The strongest implication I see is that technology could protect the character, not just threaten it. Cheaper simulators can teach strategy in winter, course sensors can save water, and better data can help designers place hazards so that skill, not distance, decides the hole. If we use the tools to keep the course a fair opponent, they're doing exactly what the game's character asks of them.",
  "What's overlooked is pace and attention. Every screen added to a round is something to look at instead of the course or your playing partners. A four-hour round already strains busy lives, and checking data makes it longer. There's also the question of who decides: equipment makers profit from each upgrade, so they aren't neutral voices. And the people who love the quiet, walking side of the game aren't usually the ones testing new products.",
  "So we agree on a lot: technology fits when it helps people learn and keeps the course a fair test, and it doesn't when it makes decisions for the player during a round. We also agree cost and pace are real concerns. What stays uncertain is where on-course aids should stop, and whether distance gains from equipment have already shifted the game more than either of us would like to admit.",
  "I'll close with the questions I'd want answered for any new gadget. Does it change a decision the player is meant to make? Does it slow the round, or make it more expensive to play well? Who benefits most, the golfer or the seller? The practical takeaway: welcome technology at the range and in the greenkeeper's shed, be cautious on the course itself, and judge each tool by whether a beginner would still recognise the game.",
];

const generic = (topic: string) => [
  `Let me open with a framing. "${topic}" sounds like a yes-or-no question, but I think it's really about trade-offs between what people gain right away and what changes slowly underneath. I'd start by naming who benefits first, who pays first, and what would have to be true for the benefits to last. That gives us something firmer than general enthusiasm or general worry.`,
  "That framing is useful, but I want to offer a different starting point. Instead of benefits and costs, I'd ask what the current situation is quietly doing well, because changes often break things nobody measured. If we can't describe what works today, we can't tell whether a new approach is an improvement or just a change. I'm not certain which framing serves us better, so let's test both.",
  "Then let me make it concrete with a small example. Imagine one place and one group of people trying the change for a single season. In the first week they'd notice the novelty and the friction. By the second month, routines settle and the real effects show up: some tasks get easier, and some get pushed onto someone else. Small trials like that are where honest evidence usually comes from.",
  "I'd test the assumption in that example, though. A small trial attracts people who already want it to work, so early results tend to look better than a wider rollout would. I'd also ask what happens at the edges: the person with less money, less time, or less say in the decision. If the change only works for the motivated middle, that's worth knowing before scaling it.",
  "Fair. Here's the strongest implication I see: the most valuable outcome may not be the change itself but what it forces people to clarify. To decide well, everyone involved has to say what they value and what they'd give up. Even if the answer is to keep things mostly as they are, that conversation leaves people with clearer priorities than they had before.",
  "The limitation we haven't covered is time. Many effects arrive slowly, after habits, prices or expectations adjust, and short trials miss them. There's also the cost of being wrong: some decisions are easy to reverse, others aren't. I'd treat anything that's hard to undo with far more caution than something you can quietly roll back after a few months.",
  "So here's our common ground: the question deserves a trial mindset rather than a verdict, and we should name who bears the costs. What remains uncertain is how well small, voluntary experiments predict wider adoption, and which effects only appear over years. I'm comfortable saying the answer differs by context. I'm less comfortable claiming we know where the line falls.",
  "I'll close with the open questions. What would a fair test look like, and who would design it? What result would change our minds? Who isn't in the room when the decision gets made? Practically: start small, measure something specific before and after, protect the people at the edges, and prefer choices you can reverse while the evidence is still thin.",
];

/** Preset topic → script, in the same order as PRESETS. */
export const PRESET_SCRIPTS: Record<string, string[]> = Object.fromEntries(
  [AI_BUSINESS, CITIES, FOUR_DAY, RESTAURANT, GOLF].map((s, i) => [PRESETS[i].toLowerCase(), s]),
);

export function scriptFor(topic: string): string[] {
  const t = topic.trim();
  return PRESET_SCRIPTS[t.toLowerCase()] ?? generic(t);
}

/** Temperature colours how each reply opens, so mock runs hint at the setting. */
const HEAT_LEADS: Record<Temperature, Record<SpeakerId, string>> = {
  calm: { A: "That's a fair concern, and it's worth taking slowly. ", B: "That's reasonable, and I'd add one careful point. " },
  lively: { A: '', B: '' },
  heated: { A: "I'm not giving that up so easily. ", B: "No, I don't buy that, and here's why. " },
};

export function mockTurnText(topic: string, seq: number, speakerId: SpeakerId, temperature: Temperature) {
  const base = scriptFor(topic)[seq - 1] ?? 'Let me pick up where we left off.';
  return (seq > 1 ? HEAT_LEADS[temperature][speakerId] : '') + base;
}
